### ISSUE TITLE
ParentChangedNotifierHelper memory leak

### ISSUE THREAD

**Issue by Nethemas** [XAMLMarkupExtensions/WPFLocalizationExtension#111]
I have encountered an issue that seems to be related to  #62 #63.  There appears to be a 
`Dictionary<WeakReference, Generic.List<Action>>` that is building up a continually growing collection.

![parentchangednotifier-leak](https://cloud.githubusercontent.com/assets/22692536/19208321/60ee2ef4-8cbe-11e6-9b83-9e7e3eeb2e5e.png)
![weakreferences-leak](https://cloud.githubusercontent.com/assets/22692536/19208363/b4b7309e-8cbe-11e6-8f21-338e47d3cc2d.png)

I chased the references around and found the leak appears to be exercised by an ItemsControl whose contents are continually updated with new (localized) child elements on a polling loop.  With each update the children are wiped and a new batch are populated.  The above dictionary however doesn't shed the entries.

**Comment by arteny** [comment]
I am getting lot of catched exceptiions "class is not visual or visual3d" when loading controls with WPFLocalizationExtension usage, they all are when WPFLocalizationExtension access internally Parent and looks they slow down loading much.
