### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by SeriousM** [XAMLMarkupExtensions/WPFLocalizationExtension#118]
Hi everyone!

As you may have noticed I'm not actively maintaining WPFLocalizationExtension.
I'm glad that the product works without that many issues and the more than 18.000 nuget downloads in two years shows me that there is still a need for such a localization solution.

I can't maintain the product anymore because wpf is not part of my daily work anymore.
@MrCircuit is not active anymore and I doubt that he want or could take it because of his family/work :(

I've seen that @xmedeko and @UeliHilfiker are answering issues. Would any of you help out or take the ownership of WPFLocalizationExtension?

Best, Bernhard

**Comment by xmedeko** [comment]
Hi, I do not know much the `WPFLocalizationExtension` internals and do not have a free time, unfortunately. I may help with some stuff around the project, like #119, or create a StackOverflow tag, make a build server, etc.

**Comment by SeriousM** [comment]
@xmedeko I just promoted you to be a maintainer. It's not meant to put pressure on your shoulders, but it's better to have two semi maintainers than just one.

**Comment by SeriousM** [comment]
@konne I guess you could help maintaining this extension together with @xmedeko, right?

**Comment by konne** [comment]
yes

**Comment by konne** [comment]
@SeriousM if you would like to phase out, I prefer to move in the future this repo in an own github org
like MarkupExtensions and move your repo and the XAMLMarkupExtensions to that place as a common place.
The good thing is on my side that we use that product and I have some employe who can spent some hours a week at this code

**Comment by SeriousM** [comment]
> to move in the future this repo in an own github org like MarkupExtensions

Thats a very nice idea! I would name it WpfMarkupExtensions. What do you think?

**Comment by konne** [comment]
I prefer a more generic name, because I really like to support Xamarin in the future to make cool Localisation Extensions also for mobile platforms available.

**Comment by SeriousM** [comment]
Alright, I like your idea. Would you create it and invite me so that I can transfer it?

**Comment by konne** [comment]
@SeriousM I invited you

**Comment by SeriousM** [comment]
thank you! the chosen name is actually the same as I was thinking about after our discussion. well done :)

**Comment by SeriousM** [comment]
I just transferred the repository to the new organization.

As the [documentation](https://help.github.com/articles/about-repository-transfers/) states:

**Comment by SeriousM** [comment]
@konne I created a nuget organization so we can publish the packages there. I used your email mattheis@ukma.de for it and you need to confirm it :)

**Comment by konne** [comment]
@SeriousM please invite the address konrad@mattheis.name, i remove the adresse ffrom the last post

**Comment by SeriousM** [comment]
it seems your email "konrad@mattheis.name" is already used by another account (yours...) which means you need to setup an organization yourself named "XAMLMarkupExtensions" (preffered name) with a new email. sorry for the issue but that's nuget...

**Comment by konne** [comment]
@SeriousM you should have an invitation to the nuget Org

**Comment by SeriousM** [comment]
Perfect, thanks!
