### ISSUE TITLE
Problem with Multiple assemblies and dictionaries

### ISSUE THREAD

**Issue by qbakk** [XAMLMarkupExtensions/WPFLocalizationExtension#124]
Hello, I have problem with use your extension in my application.
I don't know how use multi resx file in one xaml file.
For example.

I create application

```
<Window   x:Class="WpfApp5.MainWindow" 
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
             xmlns:lex ="clr-namespace:WPFLocalizeExtension.Engine;assembly=WPFLocalizeExtension"
             xmlns:system="clr-namespace:System;assembly=mscorlib"
             xmlns:extensions="http://wpflocalizeextension.codeplex.com"
             lex:LocalizeDictionary.DesignCulture="pl"
             lex:LocalizeDictionary.OutputMissingKeys="True"
                 extensions:ResxLocalizationProvider.DefaultAssembly="WpfApp5"        Title="aa" Height="300" Width="300">
    <Grid>
        <ComboBox ItemsSource="{Binding Source={x:Static lex:LocalizeDictionary.Instance}, Path=MergedAvailableCultures}"
                          SelectedItem="{Binding Source={x:Static lex:LocalizeDictionary.Instance}, Path=Culture}" 
                          DisplayMemberPath="NativeName" Width="100" Height="25"/>
        <Label Content="{extensions:Loc Test2:Test2Test}"  Width="186" Height="50" HorizontalAlignment="Left" VerticalAlignment="Top"/>
         <Label Content="{extensions:Loc Test1:Test}"  Width="100" Height="50" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="0,50"/>


    </Grid>
</Window>

```

When application start my languages work correctly but in Designer(Preview xaml file) I see that

> Key: Test2:Test2Test

In Label when I use Test1:Test in Designer resource is correcly (when I change DesignCulture
the translation changes), On the seconde label (first in code)  doesn't work. How to fix it?

I modeled myself
https://wpflocalizeextension.codeplex.com/wikipage?title=Multiple%20assemblies%20and%20dictionaries

My file structure look like:

```
WpfApp5
	Global_Resources
		Test2
			Test2.resx
			Test2.es-US.resx
		Test1.resx
		Test1.en-US.resx
		Test1.it-IT.resx

```

**Comment by SeriousM** [comment]
What about moving the test2 resx one folder up?

Am 21.12.2017 23:04 schrieb "qbakk" <notifications@github.com>:

**Comment by qbakk** [comment]
I tried but the effect is the same as I use folders for resoueces file.

**Comment by SeriousM** [comment]
It's long time ago but I guess there was something with namespace
settings... Sorry there I couldn't help you more right now

Am 22.12.2017 00:33 schrieb "qbakk" <notifications@github.com>:

**Comment by qbakk** [comment]
OK, I understand:)
Your project it works fantastic in my demo project. Today I try use it on my main application. Using a designer is very useful for our team.

The only idea I have:
- Use one resource file for all system moduls.
- Reconcile with the problem

I will check how it will behave if the resx files are in a different dll or will be in the same namespace

**Comment by SeriousM** [comment]
any updates on this one? did you managed to fix it?
