### ISSUE TITLE
Upgrade to 3.1.2 causes fails to look up resources in some cases.

### ISSUE THREAD

**Issue by serpentthegreen** [XAMLMarkupExtensions/WPFLocalizationExtension#138]
We are using WPFLocalizationExtension with DevExpress MVVM UI.
Xaml causing problems looks like this. Resource is present, access modifier is public.
```
<dxmvvm:SaveFileDialogService
      AddExtension="True"
      AutoUpgradeEnabled="True"
      DefaultExt=".cst"
      Filter="{lex:Loc LblCstFileFilter}"
      OverwritePrompt="True" />
```
This resource is not found, though. Same resource key used with menu items, for example, works and displays corresponding string.

Version 3.1.1 does not have this issue.

**Comment by xmedeko** [comment]
The problem is in the designer or running application? May you try the version 3.0.0?

**Comment by serpentthegreen** [comment]
At runtime. 
I don't remember having this issue with 3.0.0, but I'll re-check.
Will binding redirection suffice ?

**Comment by xmedeko** [comment]
Do not know, I does not have experience with binding redirection.
