### ISSUE TITLE
Nested Loc/LocText in FormatSegment1 etc. of LocText not working anymore with 3.1.x

### ISSUE THREAD

**Issue by DarkCloud14** [XAMLMarkupExtensions/WPFLocalizationExtension#139]
I'm still using LocText and its FormatSegement functionality in one of my projects.
As I experienced a memory leak with 3.0.1 I switched to 3.1.2 and that problem was solved but now a nested Loc or LocText in a FormatSegment doesn't work anymore.

I've attached [this](https://github.com/SeriousM/WPFLocalizationExtension/files/1939246/LocalizeTest.zip) sample project which at the moment is using .Net 4.7 but switching .Net Frameworks didn't solve the problem for me.

As with the new Version of WPFLocalizationExtension also comes a new XAMLMarkupExtensions version it could also be a problem of the new XAMLMarkupExtensions version.

Is there an alternative to LocText and its FormatSegment, Suffix/Prefix functionality?

**Comment by DarkCloud14** [comment]
Ok after a deeper investigation it might be a problem of the new XAMLMarkupExtensions version and so I created an issue there: https://github.com/MrCircuit/XAMLMarkupExtensions/issues/13

**Comment by konne** [comment]
Close with the prerelease nuget package of XAMLMarkupExtensions please just update
