### ISSUE TITLE
Missung properies for multiple assemblies and dictionaries

### ISSUE THREAD

**Issue by MartinEgli** [XAMLMarkupExtensions/WPFLocalizationExtension#140]
In Wiki are samples for using assemblies and dictionaries

"{lex:Loc Key=Test, Assembly=MyAssembly, Dict=MyResource}" 

But the Properties **Assembly** or **Dict** are not available

https://github.com/SeriousM/WPFLocalizationExtension/wiki/Multiple-assemblies-and-dictionaries

**Comment by adragoner** [comment]
We'll need to update the documentation as this property was marked obsolete and consequently removed in one of the early releases. You need to use the attached properties of ResxLocalizationProvider.

@MartinEgli, thanks for pointing it out.

**Comment by konne** [comment]
docu is changed
