### ISSUE TITLE
The name does not exist in the namespace "http://wpflocalizeextension.codeplex.com".	

### ISSUE THREAD

**Issue by nzain** [XAMLMarkupExtensions/WPFLocalizationExtension#142]
Since today Visual Studio 2017 Designer shows errors for all WPF localization extension references in XAML. The designer does not show user controls anymore.
> Error XDG0008
> The name "LocText" does not exist in the namespace "http://wpflocalizeextension.codeplex.com".	

- We're using this library for years now, it has worked until today for me.
- Today I upgraded to 3.1.2 (from 3.1.0), now my VS Designer is broken regardless of the version.
- I have the same problem with 3.1.0 and with latest version (3.1.2).
- Fun fact: it still works on my collegues machine (same code). He did not clear bin/obj for a while. He's running version 3.1.0. Maybe the upgrade to 3.1.2 has broken it? Not sure how.
- This is "only" a VS designer problem, the application runs fine.
- https://github.com/SeriousM/WPFLocalizationExtension/issues/131 describes the same problem, but clearing bin/obj, rebuild, and "run custom tool" does not resolve it for me.
- Tested with multiple solutions, large and tiny.

![image](https://user-images.githubusercontent.com/13961979/42086569-ca42ed3e-7b93-11e8-8109-f185dd2e89e6.png)

**Comment by nzain** [comment]
I cleared all nuget caches and reverted to 3.1.0, problem remains.

The URL on codeplex.com is forwarding, because codeplex is dead, could this be the root cause?

**Comment by nzain** [comment]
I gave up and opened the properties panel of the active xaml... and suddenly it started working again. Feel free to close this issue...

**Comment by Otiel** [comment]
>The URL on codeplex.com is forwarding, because codeplex is dead, could this be the root cause?

Just wanted to come back on this in order to have an official answer from the devs. Please correct me if I'm wrong.

    xmlns:lex="http://wpflocalizeextension.codeplex.com"

This namespace we all have to add in our xaml files is simply a reference to the namespace name stored in the library. The use of `http://` in the name is by convention, but in no way any request is done when building / running our application.

Is this right?

**Comment by konne** [comment]
yes, there is no call to this url so this is no issue

**Comment by SeriousM** [comment]
This is just a xml namespace and must not be valid.

**Comment by Otiel** [comment]
Thanks both for your reply.

@SeriousM What do you mean by "valid"?

**Comment by SeriousM** [comment]
> @SeriousM What do you mean by "valid"?

that it doesn't have to be a reachable domain/url. I could have any valid url format but without a host behind it.

**Comment by Otiel** [comment]
More than half the time I'm getting this error which prevents me from using the designer. Using the aforementioned fixes (`Build → Clean Solution`, emptying the `bin` / `obj` / `packages\WpfLocalizeExtension*` folders) doesn't help. I get the same results with VS 2017 and VS 2019.

I'm not sure what makes it work when it works.

Is there any other tip that could help solving this?

**Comment by SeriousM** [comment]
Please provide a small example project where this issue occurs so we can investigate it. thanks

**Comment by Otiel** [comment]
You can find a sample project demonstrating this here: https://github.com/Otiel/WpfLocalizeExtension-142

Thanks for taking the time to investigate this!

**Comment by UeliHilfiker** [comment]
While editing in your sample project, I got this error message: 
![image](https://user-images.githubusercontent.com/6050688/57539428-c916ce80-734a-11e9-8eb2-762b640736c6.png)

Then I downgraded the XAMLMarkupExtensions from Version 1.6.0 to 1.5.1; then it works fine... 
![image](https://user-images.githubusercontent.com/6050688/57539515-f2375f00-734a-11e9-94d6-fc6e60919d24.png)

**Comment by Otiel** [comment]
> While editing in your sample project, I got this error message:
> ![image](https://user-images.githubusercontent.com/6050688/57539428-c916ce80-734a-11e9-8eb2-762b640736c6.png)

When did you get that exception? When debugging? 😕

**Comment by Otiel** [comment]
Downgrading XAMLMarkupExtensions to v1.5.1 seems to solve this issue indeed. 👍 

Maybe a constraint should be added to the WPFLocalizationExtension nuget package in order to force it to use XAMLMarkupExtensions v1.5.1?

**Comment by UeliHilfiker** [comment]
See #193 too for this reference issue (Wrong reference to XAMLMarkupExtensions in WPFLocalizationExtension 1.6.0)

**Comment by konne** [comment]
@UeliHilfiker @Otiel @nzain @SeriousM sorry, I was longer ill and a lot of work was waiting. Now it's getting better and I will take care next week.

**Comment by klauszou** [comment]
This issue will happen at the first time when you upgrade the XAMLMarkupExtensions to 1.6.0 and build your project. If you close VS and this will dissapear. But the 3.3.1 is not compatible with XAMLMarkupExtensions v1.6.0, so when you run your project (build is ok), there will be a error. See #193

**Comment by konne** [comment]
please test the current nuget preRelease: 3.4.0-alpha0053
if there are no issues I will make next week the release
