### ISSUE TITLE
Translate itemtemplate in combobox.

### ISSUE THREAD

**Issue by redplane** [XAMLMarkupExtensions/WPFLocalizationExtension#143]
Hi,

I'm using `WPFLocalizationExtension` for my WPF app.
I have one `ComboBox` for languages selection. Item source is an `ObservableCollection<KeyValuePair<string, string>>` as below:
- `TITLE_LANGUAGE_ENGLISH` : `en`
- `TITLE_LANGUAGE_VIETNAMESE`: `vi-VN`

This is my xaml code:

```<TextBlock Text="{lex:Loc TITLE_LANGUAGE}"></TextBlock>
            <ComboBox Grid.Column="1" 
                      ItemsSource="{Binding AvailableLanguages}">
                <ComboBox.ItemTemplate>
                    <DataTemplate>
                        <TextBlock Text="{lex:Loc Key={Binding Key}}"></TextBlock>
                    </DataTemplate>
                </ComboBox.ItemTemplate>
            </ComboBox>
```

When I run the application, it throws me an exeption:

**A 'Binding' cannot be set on the 'Key' property of type 'LocExtension'. A 'Binding' can only be set on a DependencyProperty of a DependencyObject**

How can I translate the `ItemTemplate` ?

Thank you,

**Comment by xmedeko** [comment]
Do not know if this scenario is possible with `WPFLocalizationExtension`. Since resx resources are accessible from the code, I use objects with localized strings already for such scenarios. The I use simply `<TextBlock Text="{Binding Key}">`.

**Comment by redplane** [comment]
@xmedeko , your solution doesn't work. I want to translate dictionary key.

**Comment by SeriousM** [comment]
Translating keys is a bad idea. It's like letting your customer code for
you.
Solve this by having a static map between your Ressource keys ans the
custom localized keys. Then feed the Ressource key into the extension.

**Comment by redplane** [comment]
No, I'm using dictionary defined in view model. 
Key: TITLE_LANGUAGE_EN
Value: en

Key: TITLE_LANGUAGE_VIETNAMESE
Value: vi-VN

TITLE_LANGUAGE_ENGLISH & TITLE_LANGUAGE_VIETNAMESE are defined in resx file.

**Comment by xmedeko** [comment]
Revert value and key, so you will have: Key: en Value: TITLE_LANGUAGE_EN
Then simply translate the values: `dict[key] = Properties.Resources.ResourceManager.GetString(dict[key])` and use `<TextBlock Text="{Binding Value}">`. You can use a simple WPF Binding Convertor if you do not want to do it in the view model.

WPFLocalizationExtension helps a lot with common text translations, but it's not a silver bullet for everything. Do not hesitate to do a classic data conversion in view models or WPF convertors.
