### ISSUE TITLE
Binding error in Context menu

### ISSUE THREAD

**Issue by boatschl** [XAMLMarkupExtensions/WPFLocalizationExtension#144]
Hi,
I am using a context menu inside a ListBox and get flooded with this error on startup (using 3.1 and 3.1.2):

"System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor, AncestorType='System.Windows.FrameworkElement', AncestorLevel='1''. BindingExpression:Path=Parent; DataItem=null; target element is 'ContextMenu' (Name=''); target property is 'Parent' (type 'DependencyObject')"

Abbrevated WPF looks like this, the string table is set up correctly (works for all other strings in the app):
```
<UserControl>
<Grid>
<ListBox>
<ListBox.ItemTemplate>
<DataTemplate>
<StackPanel>
<Label Context="Blabla"/>
<StackPanel.ContextMenu>
<ContextMenu>
<MenuItem Header="{lex:Loc Key=Canvas.Context.Edit}"  />
```

Keep up the good work, everything else works perfectly

**Comment by xmedeko** [comment]
Are you sure your abbreviated WPF is correct? Especially the part after the `Key=`? Do not see any `RelativeSource` there.

**Comment by boatschl** [comment]
Hi,

thanks for getting back to me.
The following works fine:
`<MenuItem Header="Edit" Command="{Binding Parent.OpenModObjectDlgCommand}" />`

While this gives the error above:

> <MenuItem Header="{lex:Loc Key=Canvas.Context.Edit}" Command="{Binding Parent.OpenModObjectDlgCommand}" />

**Comment by xmedeko** [comment]
Looks like a bonding error, not the WPFLocalizationExtension error. Try to remove the the `Command="{Binding Parent.OpenModObjectDlgCommand}"` is you still see the Error in the debug output. (Of course the MenuItem will stop working, this is just a test. Then put it back again).

These WPF binding errors is another story ... It may be caused e.g. that you have no view model (`DataContext`) attached when the view is created, but it's attached later. So, everything work well, just your debug is flooded with errors.

**Comment by boatschl** [comment]
I removed the Command from the MenuItem but still get those errors.

`<MenuItem Header="{lex:Loc Key=Canvas.Context.Edit}" />`

**Comment by UeliHilfiker** [comment]
I think, the WPFLocalizationExtension cannot find the key "`Canvas.Context.Edit`". 
If `Canvas.Context.Edit` is the key in your resx, try to remove the points or change it to `Canvas_Context_Edit` for example in your resx - file and in your WPF. 


(I don't know, was is for an key there in your Resx file.)

**Comment by boatschl** [comment]
The dots are not the problem, all my other strings (> 200) use the dot notation without problems although the VS Resource Editor doesn't like it that way.

I changed my MenuItem to 
`<MenuItem Header="{lex:Loc Key=DiesIstEinTest}" Command="{Binding Parent.OpenModObjectDlgCommand}" />`
but still get the same  error.

**Comment by UeliHilfiker** [comment]
Ah, ok. 

Maybe try it in following form:
`<MenuItem Header="{lex:Loc Key=DiesIstEinTest, Assembly=MyAssembly, Dict=MyResource}" Command="{Binding Parent.OpenModObjectDlgCommand}" />`
==> replace MyAssembly and MyResource with your values used in your software.

See this wiki entry for reference:
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/wiki/Multiple-assemblies-and-dictionaries

**Comment by boatschl** [comment]
I got an compiler error when adding the Assembly and Dict parameters.
`error MC3045: Unknown property 'Assembly' for type 'WPFLocalizeExtension.Extensions.LocExtension' encountered while parsing a Markup Extension. `

Tomorrow I will try to make a quick standalone project and if I can reproduce the problem there I will attach it here.

**Comment by xmedeko** [comment]
@UeliHilfiker If the error is like the @boatschl has reported: `System.Windows.Data Error: 4 : Cannot find source for binding with reference 'RelativeSource FindAncestor ...` Then it is a WPF binding error, not a WPFLocalizeExtension error.
WPFLocalizeExtension does not write error's, you have to subscribe to the `ProviderError` event to catch missing keys and then handle it as you like.

@boatschl you may have some WPF binding problem elsewhere in the code. Check your code where you use `RelativeSource` and `AncestorType` and `Path=Parent`. It may be in your XAML, a custom WPF style or even some C# code behind.

**Comment by konne** [comment]
because of no complains of UeliHilfiker and boatschl I belive this is closed
