### ISSUE TITLE
CSVLocalizationProvider across multiple projects/assemblies

### ISSUE THREAD

**Issue by z0nghits** [XAMLMarkupExtensions/WPFLocalizationExtension#145]
Hello, I'm currently writing an app that consists of a shell project that gets functionality from multiple module projects. The shell project and each module project will supply their own set of CSV files to keep everything separate and clean.

Originally, this worked no problem when I was using .resx files for each project, all I had to do was add the following code to my Bootstrapper.cs :

            CultureInfo culture = CultureInfo.InstalledUICulture;
            LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
            LocalizeDictionary.Instance.Culture = culture;

Now that I'm switching over to CSV files, I changed it to this:

            ILocalizationProvider csvProvider = new Infrastructure.Providers.CSVLocalizationProvider() { FileName = "Lang", HasHeader = true };
            LocalizeDictionary.Instance.DefaultProvider = csvProvider;
            CultureInfo culture = CultureInfo.InstalledUICulture;
            LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
            LocalizeDictionary.Instance.Culture = culture;

This works great for the Shell project, but my modules no longer are being translated. What's the best way to enable using a CSV provider application wide? I can have each module outputted to it's own folder so all assemblies will have their own folder with their own CSV files inside.

**Comment by xmedeko** [comment]
You are using your own, custom class `Infrastructure.Providers.CSVLocalizationProvider()`, so it's hard to tell where's the problem.

The build-in `CSVLocalizationProvider` uses hard coded directory `Localization`, Dictionary  and culture name, see [CSVLocalizationProvider.GetLocalizedObject()](https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/master/WPFLocalizeExtension/Providers/CSVLocalizationProvider.cs#L170). It's not optimal, I guess this code is not much used. PRs to improve it are welcome.

However, I recommend you convert CSV to RESX so you can easily to use translated strings from the C# code, too. E.g. [ResXManager](https://marketplace.visualstudio.com/items?itemName=TomEnglert.ResXManager) has Excel import. Or you can easily make small .NET exe to do it.

**Comment by z0nghits** [comment]
Thanks xmedeko, my custom CSVLocalizationProvider is actually the one from the ProviderExample in the 3.1.2 source. I chose that over the one in WPFLocalizeExtension.Providers because it had the FileName property which I could pass the name of my CSV files. I'm relativley new to this and WPF in general, so sorry if my approach is a bit clunky.

In the built-in CSVLocalizationProvider I found where you can hard-code the directory

            // Try to get the culture specific file.
            const string csvDirectory = "Localization";

But with the following code..

// Call this function to provide backward compatibility.
            ParseKey(key, out _, out var dictionary, out key);

            // Now try to read out the default assembly and/or dictionary.
            if (string.IsNullOrEmpty(dictionary))
                dictionary = GetDictionary(target);

            // Try to get the culture specific file.
            const string csvDirectory = "Localization";
            var csvPath = "";

            while (culture != CultureInfo.InvariantCulture)
            {
                csvPath = Path.Combine(csvDirectory, dictionary + (string.IsNullOrEmpty(culture.Name) ? "" : "." + culture.Name) + ".csv");

Where exactly does the dictionary string get populated? Is it the assembly name? For example, if my app was MyApp.exe, would the CSV files be named MyApp.en-US.csv (etc) and be located in a folder called "Localization" alongside the exe?

Unfortunately a requirement is that the language files need to be human editable on disk without recompiling. So an already-compiled app when loaded will read from these files that can be easily changed by the user. I greatly prefer the RESX method, but my hands are tied.

Thanks again

**Comment by z0nghits** [comment]
Also, it's confusing because when I try to use the CSVLocalizationProvider from WPFLocalizeExtension.Providers, VS keeps complaining that 'CSVLocalizationProvider' does not contain a constructor that takes 0 arguments, when it clearly should?

After grabbing the latest 3.1.2 of WPFLocalizationExtension from here: https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/releases, when referenced in VisualStudio it says the dll is version 3.0.1.0

**Comment by xmedeko** [comment]
Yes, where the `csvDirectory` rooted is mystery for me as well. Peering at the code, looks like it may have more problems: not possible to change delimiter, no escaping of delimiter and new line, i.e. no robust CVS parsing.
@konne @SeriousM The CSV is not well defined format, users may have different formats and differnet libaries (e.g. TinyCsvParser, CsvHelper, FileHelpers, ...). So I suggest to polish the `CSVLocalizationProviderBase`, and move the  `CSVLocalizationProvider` to the `ProviderExample`. So every user may just extent `CSVLocalizationProviderBase` and plug in own file resolution and own CSV parsing.

@z0nghits I suggest you to debug and fix your `CSVLocalizationProvider`, also look into the `CSVLocalizationProviderBase` and `CSVLocalizationProvider` in the code if they may be useful for you.

**Comment by konne** [comment]
@xmedeko please just make a new feature request for the CSV Provider, we will see to get this into the roadmap

**Comment by z0nghits** [comment]
Thanks, I was able to get my Shell project working with CSV files using the CSVLocalizationProvider from ProviderExample for now by setting the FileName property.

Is there currently any approach for getting other modules to work as well? I imagine each module would have to modify the FileName since each set of CSVs are located in different folders. Or would each module have it's own instance?

**Comment by xmedeko** [comment]
Use `assembly:` in the change the line `ParseKey(key, out _, out var dictionary, out key);` to ParseKey(key, out var assembly, out var dictionary, out key);`.

**Comment by xmedeko** [comment]
@z0nghits see also #146 I suspect the `CSVLocalizationProvider` reads the CSV file for every new key.
