### ISSUE TITLE
Remove CSVLocalizationProvider from the project

### ISSUE THREAD

**Issue by xmedeko** [XAMLMarkupExtensions/WPFLocalizationExtension#146]
The `CSVLocalizationProvider` is not well implemented and it cannot be well implemented for each user:
- See #145
- Fixed file name and location, not relative to assembly.
- CSV file is not cached (!) - it's parsed for every key.
- No fallbacks to default locale for missing keys. E.g. a key is missing in the `land_de_at.csv`, get one from the `lang_de.csv`, is missing then one from `lang.de`. However, this feature may be hard to implement so it may be omited. 
- CSV not parsed well:
  - Not possible to change delimiter.
  - Not escaping delimiter, new lines.
  - CSV has no fixed format, more libraries exists to parse it well (TinyCsvParser, CsvHelper, FileHelpers, ...). However, each parser must be configured prior the work.

We should not make any solution based on one CSV parser. Instead I suggest to make a good base class so as a user may plug in own file name and CSV parser easily:
1. Make some common `LocalizationProviderBase`.
2. Make `CsvLocalizationProviderBase extends LocalizationProviderBase` so as it's straightforward to extend it.
3. Remove `CSVLocalizationProvider` from the base code. Rename the `ProviderExample` to the `CsvProviderExample` and refactor the `CsvProviderExample.CsvLocalizationProvider` to extend `CsvLocalizationProviderBase`.

**Comment by konne** [comment]
follow up in #243
