### ISSUE TITLE
Set resource value in setter property.

### ISSUE THREAD

**Issue by hnmange** [XAMLMarkupExtensions/WPFLocalizationExtension#147]
I am following "ControlName_PropertyName" for auto key retrieval. I have many buttons in my form so can I apply style and set "tooltip" property using setter property like 

<Style x:Key="StyleButtonTransparent" TargetType="{x:Type Button}">
<Setter Property ="ToolTip" Value="{lex:Loc}"/>
</Style>

I have tried this but not working. Any help ?

**Comment by konne** [comment]
Hi, I don't see the issue with the Loc Extension. Please can you write a longer example with a reference to this library

**Comment by hnmange** [comment]
Thanks @konne for reply.  Here is the example.

<Window x:Class="LocalizationDemoUsingNuget.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:lex="http://wpflocalizeextension.codeplex.com"
        lex:LocalizeDictionary.DesignCulture="en"
        lex:LocalizeDictionary.OutputMissingKeys="True"
        lex:ResxLocalizationProvider.DefaultAssembly="LocalizationDemoUsingNuget"
        lex:ResxLocalizationProvider.DefaultDictionary="Resources"    
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Window.Resources>
        <Style x:Key="buttonStyle" TargetType="{x:Type Button}">
            <Setter Property="Height" Value="50"/>
            <Setter Property="Width" Value="50"/>
            <Setter Property="Content" Value="{lex:Loc}"/>
        </Style>
    </Window.Resources>
    <Grid Height="200" Width="200">
        <StackPanel Height="200" Width="200">
            <Button x:Name="btn1" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn2" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn3" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn4" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn5" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn6" Style="{StaticResource buttonStyle}"/>
            <Button x:Name="btn7" Style="{StaticResource buttonStyle}"/>
        </StackPanel>       
    </Grid>
</Window>

So, will it work if I provide content of button in style ? I have created resource file and values for all button content is available in resource file with naming convention "ControlName_PropertyName" . In my case it's like btn1_Content, btn2_Content ...

**Comment by konne** [comment]
@hnmange sorry, but I stell see no XAML Attributes / Markupextensions,.. that points on the usages of the WPFLocalizationExtension

**Comment by HoytRen** [comment]
However you can assign a x:Name or x:Uid to a setter in xaml, these property isn't exist in code, I guess only the xaml engine use them when parse your xaml and then they are unknown, so the auto key retrieval feature never works for setter, and you have to provide a key. Bad news for me too.
