### ISSUE TITLE
Removing NeutralResourcesLanguage from AssemblyInfo.cs

### ISSUE THREAD

**Issue by aetaylor** [XAMLMarkupExtensions/WPFLocalizationExtension#148]
In the Common Mistakes section you recommend removing the following line from AssemblyInfo.cs:
 `[assembly: NeutralResourcesLanguage("en-US", UltimateResourceFallbackLocation.MainAssembly)]`

If I leave this line in then all text is always localised to the neutral language, so I understand why it should be removed.
However, if I remove it then the application will not run. It throws an exception complaining that it cannot find app.xaml.
Do you have any idea why this would be?

**Comment by konne** [comment]
@aetaylor sorry, no idea. Can you please provide a small example

**Comment by aetaylor** [comment]
Hi, I re-installed the NuGet package and everything is working now.
