### ISSUE TITLE
Having trouble getting things wired up.

### ISSUE THREAD

**Issue by davidleedom** [XAMLMarkupExtensions/WPFLocalizationExtension#149]
I'm having trouble getting things to work.  I know I'm missing something dumb.
I have tried to reproduce the same type of example as the SatelliteAssemblyTest, but i'm having no luck.

For one thing it appears that in your example resource (resx) files are creating in language folders and DLLs but mine are not.  I'm sure there is something fundamentally obvious I don't understand about the setup.
[WPFDavidLeedomExperiment.zip](https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/files/2300806/WPFDavidLeedomExperiment.zip)

David Leedom

**Comment by davidleedom** [comment]
My problem was the language name.  I am trying to translate Serbian Latin.  Which has a code of **sr-SP-Latn**.  So I was naming the source file.  **Language.sr-SP-Latn.resx**.    This was wrong.  I must only use the two letter ISO code for the language.  I did not understand this until I dug into things some more.

**Comment by UeliHilfiker** [comment]
Use one of this language code for serbian:
![image](https://user-images.githubusercontent.com/6050688/44336562-221a9b80-a478-11e8-826c-a58c0f6fa23b.png)

I has retrieved this language codes from .NET framework.

**Comment by UeliHilfiker** [comment]
To list all supported language codes: 

in VB.NET
```vb.net
    Private Sub listAllSupportedLanguagesToDebugOutput()
        Dim cultures() As Globalization.CultureInfo = Globalization.CultureInfo.GetCultures(Globalization.CultureTypes.AllCultures)
        Dim cult As New List(Of Globalization.CultureInfo)
        cult = cultures.ToList

        Dim sortedCultures = From c In cult Order By c.DisplayName

        For Each ci As Globalization.CultureInfo In sortedCultures
            Debug.Print(String.Format("{0} - {1} - {2} - {3}", ci.Name, ci.DisplayName, ci.EnglishName, ci.NativeName))
        Next
    End Sub
```

in C#
```C#
private void listAllSupportedLanguagesToDebugOutput()
{
    System.Globalization.CultureInfo[] cultures = System.Globalization.CultureInfo.GetCultures(System.Globalization.CultureTypes.AllCultures);
    List<System.Globalization.CultureInfo> cult = new List<System.Globalization.CultureInfo>();
    cult = cultures.ToList();

    var sortedCultures = from c in cult
                         orderby c.DisplayName
                         select c;

    foreach (System.Globalization.CultureInfo ci in sortedCultures)
        Debug.Print(string.Format("{0} - {1} - {2} - {3}", ci.Name, ci.DisplayName, ci.EnglishName, ci.NativeName));
}
```

**Comment by davidleedom** [comment]
@UeliHilfiker Thanks for the feedback and code examples.  I just got things working on an experimental level.  I need to do some additional playing around to make sure I understand how this all works.
