### ISSUE TITLE
Strong-named assembly

### ISSUE THREAD

**Issue by superware** [XAMLMarkupExtensions/WPFLocalizationExtension#150]
It's impossible to reference WPFLocalizationExtension from a strong-named assembly, can you please strong-name WPFLocalizationExtension (and XAMLMarkupExtensions)? I don't think this is a breaking change, but will certainly allow broader usage. Thanks!

**Comment by SeriousM** [comment]
Try use the search functionality, this issue was discussed many times
before.

**Comment by jozefizso** [comment]
We must have our assembly signed with strong name and this prevents us from using the WPFLocalizationExtension library. :(

**Comment by xmedeko** [comment]
@superware @jozefizso see #141 
Please, search old issues before you report a new one.

**Comment by SeriousM** [comment]
[C# 7.3](https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7-3) has a new compiler flag to sign assemblies!
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/publicsign-compiler-option

@konne whats your thought about that?

**Comment by konne** [comment]
@SeriousM I will have a look at this and will play a little bit with that nice new option.
I'm shure in the end we will have two nuget packages, but with an fully automated compile
and upload process this is not an issue.

**Comment by konne** [comment]
@SeriousM @jozefizso @xmedeko 
the new prerelease WPFLocalizeExtension.3.4.0-alpha0016.nupkg is public signed please test and give a feedback

**Comment by konne** [comment]
@superware can you give a feedback of the now signed preRelease
@jozefizso ??

**Comment by konne** [comment]
no reaction, I will close it

**Comment by MikeFarrington** [comment]
I see that the nuget package WPFLocalizeExtension has the .3.4.0-alpha0016, but WPFLocalizeExtension.Signed has no pre-releases and hasn't been updated since August for v3.1.2.

Oh, after digging I see that someone unaffiliated by the name of " jozef.izso" put that out.  Should I "Report Abuse" on nuget.org so you guys can take ownership of that, or will you publish the final signed package under a different name?

**Comment by konne** [comment]
@MikeFarrington yes you can Report that to nuget. I don't know how the abuse process works / how long does it take.

**Comment by MikeFarrington** [comment]
I didn't want to jump straight to "Report Abuse", so I sent this person an email asking them to reach out to you to assign the package over to you since you're getting ready to release a signed version (thank you for the signed version btw).

**Comment by MikeFarrington** [comment]
I found him on GitHub, so, I'll tag him in case he doesn't see my email.  @jozefizso

**Comment by jozefizso** [comment]
Uhm, the package does not abuse anything.

It was created because we needed a signed version of the package at the time. Our product depends on that package.

Nuget users can see there's a new version of the official package and that it is signed.

**Comment by MikeFarrington** [comment]
@jongleur It was created with the best intentions, I get that.  That's exactly why I didn't report it (after initially suggesting it -- I thought better of it).  They want to move forward with both a signed and unsigned package, and the official-sounding package name you chose conflicts with the standard convention of tacking on .Signed to an existing unsigned package.

**Comment by xmedeko** [comment]
@jozefizso Yep, it's nice when unofficial packages have different names to clearly distinct it's not the original project.  You may append "-Unofficial", append your name or nickname, or choose completely different name. Unfortunately, nuget has plenty of such unofficial packages with similar names and it's confusing for the end users.

**Comment by konne** [comment]
@jozefizso the "main" packge is now signed, so you should be able to easily remove your package.
thx
