### ISSUE TITLE
File version for WPFLocalizationExtension and XAMLMarkupExtensions is 0.0.0.0

### ISSUE THREAD

**Issue by alanwol** [XAMLMarkupExtensions/WPFLocalizationExtension#167]
File version for WPFLocalizationExtension and XAMLMarkupExtensions is 0.0.0.0. When checking the details of WPFLocalizationExtension.dll and XAMLMarkupExtensions.dll the file version seems to be not set. This breaks the installer for our software, which checks the file version or product version. Previous version had the file and product version set to the nuget package version.

**Comment by konne** [comment]
@alanwol  I will check this asap

**Comment by konne** [comment]
@alanwol thanks, please test the new nuget WPFLocalizeExtension 3.3.1
If you have any issues, just reopen the ticket

**Comment by alanwol** [comment]
I've checked the new packages and they have the file version and product version set now. I hope this solves the issue with the installer, in any case I consider this issue resolved.
