### ISSUE TITLE
Remove Key:

### ISSUE THREAD

**Issue by Skuriles** [XAMLMarkupExtensions/WPFLocalizationExtension#180]
Hello all,

I've already read this issue:
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/103

but at the end it only gives the opportunity to show a not translated string with "key:" prefix or not at all.

So my question is:
Is there a way to show the translated resource string if available and if no resource is available, just show the key without "Key: " Prefix. 

Background:
We use json files to create dynamic controls in a WPF:
```
<lex:LocProxy Source="{Binding Path=Lable, Mode=OneTime}"
                      x:Name="Proxy" />
        <Label Content="{Binding Result, ElementName=Proxy}" Grid.Row="0" Grid.Column="0" HorizontalAlignment="Left"
               VerticalAlignment="Center" FontSize="16" />
```
But if the Lable property is not found in Resx files it shows "Key: <LableStr>" instead of "LableStr.
Is this possible?
OutputMissingKeys only gives the opportunity to hide the strings at all.

Thanks in advance

**Comment by konne** [comment]
@Skuriles You should see Key: and the real requested key.
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/pull/123/files
Do you really see only "Key:" and nothing else?

**Comment by Skuriles** [comment]
For sure I see "Key: <requestedKey>" but what I want is that is only "<requestedKey>" without the "Key:" prefix. 
I've already checked the file in your link, this is why I asked if there is another option to achieve is.
Problem can be, that a customer can add any key in the json file and if this key is not in the translation resources there is this "Key:" prefix.

**Comment by konne** [comment]
@SeriousM @xmedeko what do you think? Do we may remove the "key: " from the code or allow it to remove with an Global Static / AttachedProperty Setting?

**Comment by xmedeko** [comment]
@Skuriles common workaround for this is to fill the default resx file with the string you want. So, instead of missing resource, make the resource value same as the key.

@konne if you want to have configurable output for missing key, I think instead of static property is would be better to do it programmatic way:
- Either in the `MissingKeyEvent` event (e.g. add `Value` property to the event.)
- Or some virtual method like `protected virtual LocalizeDictionary.GetMissingKeyValue(string key) => "Key: " + key;'` So the user may overwrite it.

**Comment by konne** [comment]
@xmedeko 
> * Either in the `MissingKeyEvent` event (e.g. add `Value` property to the event.)
I like the idea of that Event. This also gives a good possibility as software to log for example missing keys into files.

**Comment by Skuriles** [comment]
> @Skuriles common workaround for this is to fill the default resx file with the string you want. So, instead of missing resource, make the resource value same as the key.
> 
> @konne if you want to have configurable output for missing key, I think instead of static property is would be better to do it programmatic way:
> 
> * Either in the `MissingKeyEvent` event (e.g. add `Value` property to the event.)
> * Or some virtual method like `protected virtual LocalizeDictionary.GetMissingKeyValue(string key) => "Key: " + key;'` So the user may overwrite it.

Just to be clear (no offense, but I want to show you our workflow):
There is a customer in US or China who changes the configuration of the software. He never sees the resx files. For practical reason no one will write/call the supplier, who ask us (dev team) to change the resx files because he simply changed a lable name in his configuration, then we have to change it, compile a new version of the file and do a worldwide update for all customer to be compliant with version numbers etc,. He just want to see what he has entered and don't want to see "Key: <lablename>" or do an update for this. 
Sure we can give a list with allowed keys, but everybody knows customers, don't we?

So it can't be simply done by "add a empty resx entry" or something similar. 

A trigger to hide the "Key:" prefix would be nice or at least a possibility to overwrite the transform function.

**Comment by xmedeko** [comment]
@konne `MissingKeyEvent` already exists.  I use it to log missing resources already 😃

**Comment by UeliHilfiker** [comment]
Just my opinion: 
It is best to leave the "key:" prefix if the key is missing, because it is a very useful function for us. We should keep this behavior as default. 
It's best to make it switchable, or configurable, so that you can switch if you don't want to have a key prefix.

**Comment by xmedeko** [comment]
@Skuriles one solution you can implement now: Make a subclass of `ResxLocalizationProvider`, override `GetLocalizedObject` and return whatever you want if the `base.GetLocalizedObject()` returns `null`. Then, intialize your app like:
```c#
internal static void Configure()
{
    var provider = MyResxLocalizationProvider.CreateInstance();
    // Optional: set default assembly
    // provider.FallbackAssembly = 
    LocalizeDictionary localizeDictionary = LocalizeDictionary.Instance;
    localizeDictionary.DefaultProvider = provider;
    // optional, for logging missing keys
    // localizeDictionary.MissingKeyEvent += LocalizeDictionary_MissingKeyEvent;
}
```

**Comment by Skuriles** [comment]
Thanks @xmedeko 
Final solution to get only the string:

` public override object GetLocalizedObject(string key, DependencyObject target, CultureInfo culture)
        {
            var result = base.GetLocalizedObject(key, target, culture);
            if (result == null)
            {
                var keyRes = base.GetFullyQualifiedResourceKey(key, target);
                Type type = keyRes.GetType();
                return type.GetProperty("Key").GetValue(keyRes).ToString();
            }

            return result;
        }`
