### ISSUE TITLE
Tutorial is not clear

### ISSUE THREAD

**Issue by maks-ua** [XAMLMarkupExtensions/WPFLocalizationExtension#182]
Dear developers,

I'm sorry for my stupid question. I am new in WPF and your wiki was not clear for me.
I don't understand what steps I should take to make it work and I havn't found an appropriate tutorial in Internet.
Could someone reccomend me a tutorial or briefly describe steps needed to do.

Thank you in advance!

**Comment by konne** [comment]
Hi, I work at the moment on the examples to make them running and better in the documentation.
But everything what you need to do is, add nuget and than:
0. https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/wiki/Resource-files
1. https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/wiki/Preparing-the-XAML-code
2. https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/wiki/Our-first-localized-text

**Comment by maks-ua** [comment]
Thank you very much for your rapid responce.
That was my fault, i havent seen my failure.
