### ISSUE TITLE
Text is not shown in preview

### ISSUE THREAD

**Issue by maks-ua** [XAMLMarkupExtensions/WPFLocalizationExtension#183]
Dear Developers,

when I use Automatic key retrieval {lex:Loc} Texts are not shown in the preview mode of VS, but only after compilation.
There are just blank spaces in preview mode and it can confuse one designing the layout.
Is there any possible solution for it?

Thank you in advance.

**Comment by konne** [comment]
Hi,
the support of the preview in VS is in the product but not "supported". The WPF Designer in VS is sometimes strange. We have in the code a lot of special cases to get this working, but not 100%.
Very often complete close + restart of VS helps. I use at the moment VS2017 with actual patches and in my projects its working great.
