### ISSUE TITLE
Localize without XAML

### ISSUE THREAD

**Issue by maks-ua** [XAMLMarkupExtensions/WPFLocalizationExtension#184]
Dear developers,

I have to localize some strings direct in Code without XAML in different languages.
Could you suggest me a possible solution?

Thank you in advance.

**Comment by xmedeko** [comment]
The goal of this library is to use RESX in XAML, but you can use RESX in .NET languages (C#, ....) without any problem, see https://docs.microsoft.com/cs-cz/dotnet/framework/resources/working-with-resx-files-programmatically

**Comment by maks-ua** [comment]
Thank you very much!

**Comment by konne** [comment]
@maks-ua even if it is closed. You could also write your own TranslationProvider that delivers the data from classes / attributes,..

**Comment by maks-ua** [comment]
@konne of course, I'm sorry for the late answer
`
public class LocalizationProvider

    {
        public static String GetLocalizedValue(string key)
        {
            CultureInfo ci = new CultureInfo(language); //language should be passed here

            Assembly ass = Assembly.Load("ProjectName"); 

            ResourceManager rm = new ResourceManager("ProjectName.Folder.Strings", ass);

            return rm.GetString(key, ci);
        }
    }
`

This works perfectly with different language resx files.
Im currently try to implement an append function in case if the key doesnt exist in the Strings.resx
I use ResourceWriter.AddResource() but cannot get correct path of the file: it is looking for the file on my Desctop...

If someone has ideas, please share them.

Best regards,
Maks

**Comment by maks-ua** [comment]
The solution is pretty simple:
```
 if (rm.GetString(key, ci) == null)
            {
                string root = Path.GetDirectoryName(Assembly.GetCallingAssembly().Location);
                string file = "TODOStrings";
                string path = String.Format(@"{0}\{1}.{2}.txt", root, file, ci);

                if (!File.Exists(path))
                {
                    using (StreamWriter sw = File.CreateText(path))
                    {
                        sw.WriteLine(key);
                    }
                }
                else
                {
                    string[] readText = File.ReadAllLines(path);
                    foreach (string s in readText)
                    {
                        if (s == key) break;
                        else
                        {
                            using (StreamWriter sw = File.AppendText(path))
                            {
                                sw.WriteLine(key);
                                break;
                            }
                        }
                    }
                }
            return $"Key: {key}";
            } 
            else return rm.GetString(key, ci);
```
