### ISSUE TITLE
Remove GapTextControl 

### ISSUE THREAD

**Issue by konne** [XAMLMarkupExtensions/WPFLocalizationExtension#186]
I see no need that this control is part of the WPFLoaclizationExtension.
This extension doesn't solve the need of Translations with FormatesStrings and Parameters like:
"The number of incidents: {0} should be solved",...

**Comment by konne** [comment]
@SeriousM @xmedeko 
What do you think about this.
I like to make a breaking 4.0 release that removes this and #146

**Comment by SeriousM** [comment]
It's OK to me, I was not a fan of the gap text in the first place.

**Comment by xmedeko** [comment]
I do not use that either. If somebody likes that, then he/she can just copy&paste the code.

**Comment by konne** [comment]
Hi, I really like to introduce here a new discussion about the issue of GapTexts for Translation purpose. There is still a need have have for example: "The house have {0} doors" with the paramter that should be bound with Binding to the datamodel.

There are general issue that make this not easy:
1. Binding Parameters can not be changed after the binding is running.
2. Bindings can not be an attribute in an MarkupExtension because this is not a child of DependencyObject

The best would be to set the Translationmessage just a StringFormat and pass the Parameters as extension. My suggestion is now to go the following way:

Use a multibinding with an Converter.
The first **parameter** is the StringFormat
All others are parameter.
```XML
<element.Text>
    <MultiBinding Converter={lex:StringFormatConverter}>
        <lex:BLoc Path="assembly:resource:key" />
         <Binding Foo />
         <Binding Bar />
         <Binding ... />
    </MultiBinding>
</element.Text>
```

In the future I also think of to integrate [SmartFormat](https://github.com/axuno/SmartFormat/wiki) so that we have even a possibility to have real i18n with pluralization,...

Please give me feedback: @SeriousM @xmedeko  @Karnah @SingThatSong @mihaicupsuite @redplane @UeliHilfiker

**Comment by konne** [comment]
@sa-he please also have a look

**Comment by xmedeko** [comment]
I am not developing in C#, so not using WPFLocalizationExtension.  My previous opinion is https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/171#issuecomment-457190764 . Formatted style of messages requires skilled translators or the translators has to cooperate with developers to make formatted translations properly, which increases the cost of localisation. So, one must weight pros and cons. 

If you want to use `SmartFormat` for plurals you have to use https://github.com/axuno/SmartFormat/wiki/Pluralization - some languages have complex rules, with as many as 6 plural forms.

**Comment by sa-he** [comment]
I personally try to avoid gap texts like the GapTextControl provides. Most of the times there is a simpler way to display the same information.

Your suggested replacement (multibinding + converter) for GapTextControl is less powerfull but easier to maintain. I'd say the features of GapTextControl (like inserting UserControls into gaps) is a usecase which can be dropped.

In short: I like your suggestion.

**Comment by konne** [comment]
add instance and markupextension for cleaner xaml without staticresource for converter http://drwpf.com/blog/2009/03/17/tips-and-tricks-making-value-converters-more-accessible-in-markup/

**Comment by konne** [comment]
see #243

**Comment by konne** [comment]
new preRelease is online: 3.7.0-alpha.45.nupkg

**Comment by konne** [comment]
follow up in #243
