### ISSUE TITLE
When debugging (F5) everything is ok. If i run the app (STRG+F5) no translation...

### ISSUE THREAD

**Issue by Aitania** [XAMLMarkupExtensions/WPFLocalizationExtension#192]
When debugging (F5) everything is ok. If i run the app (STRG+F5) no translation...
i have tried with old an new version of WPFLocalizationExtension. 
This problem appeard since i have a lot of keys in resource files. About 550 keys.
Erlier with less keys i din't notice this problem.
I am  not sure if this is a WPFLocalizationExtension problem.
I have created the files with ResXManager but sommetimes i made changes to these 
resources manually, directly in the files.

**Comment by Aitania** [comment]
Sorry... It was my mistake! Everything is ok!

**Comment by SeriousM** [comment]
Would you tell us the story? Maybe we can learn something?
