### ISSUE TITLE
Update to use XAMLMarkupExtensions v 1.6.0 

### ISSUE THREAD

**Issue by benjaminrupp** [XAMLMarkupExtensions/WPFLocalizationExtension#193]
Please update to use XAMLMarkupExtensions v 1.6.0 because this includes some bugfixes.

Currently I'am getting the following error message if I'm using v1.6.0:

Error	
CS0012	
The type 'NestedMarkupExtension' is defined in an assembly that is not referenced. You must add a reference to assembly 'XAMLMarkupExtensions, Version=1.5.1.0, Culture=neutral, PublicKeyToken=null'.

Thanks

Benjamin

**Comment by arminaFr** [comment]
I'm experience this issue, as well. I'm able to update XAMLMarkupExtenssion up to 1.5.1 but not any further. When I update it to 1.6.0, I got "HRESULT: 0x80131040: The located assembly's manifest definition does not match the assembly reference" error in my tests.

**Comment by mcanyucel** [comment]
This issue still persists; it looks like the latest compatible XAMLMarkupExtension is 1.5.1. I had to downgrade to make the app work again.

**Comment by DaveLaa** [comment]
This issue is still existing. Why nobody fixes it? We cannot use the new version 1.6. because of this silly bug. Its so sad for the developers that we are all stuck on V1.5.1 and noone ca use the new features...

**Comment by konne** [comment]
@benjaminrupp please test the current nuget preRelease: 3.4.0-alpha0053
if there are no issues I will make next week the release

**Comment by benjaminrupp** [comment]
Thank you!
It is working for me 😊

Von: Konrad Mattheis <notifications@github.com>
Gesendet: Mittwoch, 8. Januar 2020 12:00
An: XAMLMarkupExtensions/WPFLocalizationExtension <WPFLocalizationExtension@noreply.github.com>
Cc: Rupp, Benjamin <Benjamin.Rupp@hte-company.de>; Mention <mention@noreply.github.com>
Betreff: Re: [XAMLMarkupExtensions/WPFLocalizationExtension] Update to use XAMLMarkupExtensions v 1.6.0 (#193)


@benjaminrupp<https://github.com/benjaminrupp> please test the current nuget preRelease: 3.4.0-alpha0053
if there are no issues I will make next week the release

**Comment by nucasspro** [comment]
It's still error :(

**Comment by lutz** [comment]
Is there a date to release the final 3.4?
