### ISSUE TITLE
Support of Framework.Net resources

### ISSUE THREAD

**Issue by BeePerNet** [XAMLMarkupExtensions/WPFLocalizationExtension#196]
To be able to use that in xaml: ="{lex:Loc Key=PresentationCore:ExceptionStringTable:DeleteText}"

I had to add an if to make it works. I think that it is not the best way, I did not check the whole structure.

WPFLocalizeExtension.Providers.ResxLocalizationProviderBase
~Line 482

>                     resManager = GetResourceManagerFromType(resourceManagerType);
>                 }
>                 else
>                 {
>                     if (resManagerNameToSearch.StartsWith("."))
>                     {
>                         resManagerNameToSearch = resManagerNameToSearch.Remove(0, 1);
>                         resManagerNameToSearch = resManagerNameToSearch.Replace(ResourceFileExtension, string.Empty);
>                     }
>                     resManager = new ResourceManager(resManagerNameToSearch, assembly);
>                 }

**Comment by konne** [comment]
@BeePerNet I justed merged the PR so this will be in the next release. I will close that issue
