### ISSUE TITLE
EnumComboBox only runs with V2.3.2 and older

### ISSUE THREAD

**Issue by BerndExOne** [XAMLMarkupExtensions/WPFLocalizationExtension#203]
Hello, we have the Little issue, that "EnumComboBox" runs good with WPFLocalizationExtensions
V 2.3.2, but not good with a newer Version. That means, the resource translations are OK in this Combo box with the old Version, but if there is a newer Version then the Combo box items are shown as "key: …"

**Comment by Rainer1** [comment]
I have the same issue in my project. Locked to V2.3.2, since newer versions don't translate my EnumComboBox!
It would be great, if you could fix that!

**Comment by konne** [comment]
please change a sample and make a PR, I tested the GapTextWpfTest and everything works fine. (see PR #244)
