### ISSUE TITLE
MissingKeyEvent not raised when using LocalizeDictionary.Instance.GetLocalizedObject()

### ISSUE THREAD

**Issue by wowfood** [XAMLMarkupExtensions/WPFLocalizationExtension#206]
.Title says it all really.

I've got some code in my ShellView which we use for capturing missing resource keys, which for the most part works fine, however i've recently noticed that if you use the LocalizeDictionary.Instance.GetLocalizedObject() method, if it fails to find the key the MissingKey event isn't raised.

Reason we switched to using the GetLocalizedObject method is because we get our resource IDs from bindings.  Originally we had been using LocProxy, however noticed that on pages with many controls, this was incredibly slow, hence the switch.

**Comment by konne** [comment]
Hi, the issue behind is that the **MissingKey** Event is generated in the **LocExtension** and this is not used.
You can only use the **LocalizeDictionary.Instance.DefaultProvider.ProviderError** and search for the Message Missing Key,

I know that this is from the architecture not perfect and I will document this, but a real change has to much sideeffects.
