### ISSUE TITLE
Include StringFormatProxy

### ISSUE THREAD

**Issue by SingThatSong** [XAMLMarkupExtensions/WPFLocalizationExtension#214]
I was looking for a way to localize StringFormat and found StringFormatProxy, which sits in the tests project. Is there any reason it's not main library? Maybe there is another way to localize StringFormat?

**Comment by konne** [comment]
@SingThatSong Nop, I fully understand your request but I really like to handle this issue in a more generic approach inside of the lib.
Please follow the discussion #186
