### ISSUE TITLE
Upgrade 2.3.2 to 3.3.1 slows down Application start

### ISSUE THREAD

**Issue by darinkes** [XAMLMarkupExtensions/WPFLocalizationExtension#215]
Users noticed a slow down of an application, after the WPFLocalizationExtension Nuget was updated from version 2.3.2 to 3.3.1. The issue was pinned to this update by just downgrading this Nuget in the Application back to version 2.3.2.

The loading time of the application went on my machine from about 5 seconds to about 60 seconds.

Tracing with procmon-Tool from Microsoft shows with version 3.3.1 the application tries to open various Culture-Resource dlls, which don't exist. Starting from "aa" to "zh-CHT". Which takes about 45 to 60 seconds. We just ship dictionaries for "en" and "de".

Why does WPFLocalizationExtension behave this way after upgrading it and how can we prevent those slow startup times?

My first idea was to tell WPFLocalizationExtension we just want "en" and "de", but I couldn't find a way to achieve this.

Thanks in advance

**Comment by darinkes** [comment]
I suspect its this code, where it tries to load all cultures:
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/master/src/Providers/ResxLocalizationProviderBase.cs#L500

**Comment by Jeverson28** [comment]
Hi, not sure if it's due to the same thing but I had the same issue. I made a comment in another Issue here with my solution. I hope it helps, although I am aware my situation was rather niche.
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/issues/181#issuecomment-572997938

**Comment by konne** [comment]
@darinkes please test the newest release. If you still have an issue open the this issue again and please add a small Demo app in tests or extend an existing demo app
