### ISSUE TITLE
Perfomance degradation / memory leak using TextBlock.InlineCollection

### ISSUE THREAD

**Issue by Karnah** [XAMLMarkupExtensions/WPFLocalizationExtension#222]
Hello. First of all - thanks for amazing library. 
We have TextBlock with InlineCollection inside ItemsControl. ItemsSource of ItemsControl is changing many times during application running. Sample of TextBlock:
``` xaml
<TextBlock FontSize="20">
    <Run Text="{lex:LocText Hello}" />
    <Run FontWeight="Bold" Text="{lex:LocText Wonderful}" />
    <Run Text="{lex:LocText World}" />
</TextBlock>
```

**Problem**
Every next render is slower then previous when ItemsSource changed. I created [sample of this problem](https://github.com/Karnah/WPFLocalizationExtension.LeakSample). Run it and press "Reload" button many times. Аfter about 60-80 clicks you can see perfomance degradation.

**Comment by konne** [comment]
@Karnah you can remove your repo. I have added this to the /tests directory inside this repo. If you like to extend this tests please make changes here, so that we can track chances in a consit way.

I will close that issue
