### ISSUE TITLE
Use Microsoft.Extensions.Localization

### ISSUE THREAD

**Issue by beachwalker** [XAMLMarkupExtensions/WPFLocalizationExtension#223]
It would be nice if this extension would build against Microsoft.Extensions.Localization instead of direct dependency to local Resource files. IMHO this is the way to go for Net Core.

See https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.localization?view=dotnet-plat-ext-3.1

Especially see the IStringLocalizer interface:
https://docs.microsoft.com/de-de/dotnet/api/microsoft.extensions.localization.istringlocalizer?view=dotnet-plat-ext-3.1

There is a builtin implementation which resolves from properties by default.

**Comment by konne** [comment]
@beachwalker I would be happy if you contribute with an PR to that topic
If you need any help just contact me

**Comment by konne** [comment]
@beachwalker I don't really understand your need. Yes the libraries in the backend are doing some stuff that we are doing but in the end the user has to add the same resx files like today. I only found [ASP Localization](https://docs.microsoft.com/en-Us/aspnet/core/fundamentals/localization?view=aspnetcore-3.1) as an example for this usage.
If this libraries from MS are backported to .NET we can think of to use them as the resx resolving backend, but at the moment we still have to take care of them.

I will close that ticket for now. I you have code samples & good arguments please reopen it.
