### ISSUE TITLE
Add CLA

### ISSUE THREAD

**Issue by konne** [XAMLMarkupExtensions/WPFLocalizationExtension#227]
add a sign process for the contribution license aggrement to be shure that contribution of code in PR is free of sideeffects

**Comment by konne** [comment]
@SeriousM sorry that I don't discussed this planned changed upfront with you. Please let us use this issue to discuss that change.

As my understanding the CLA doen't effect the MS-PL

**Comment by konne** [comment]
ref #228

**Comment by SeriousM** [comment]
Adding this checks seems to be a good idea! I was just wondering if you
were about to change the license :)
