### ISSUE TITLE
Make TaranslateConverter.Convert(object value, ..) virtual

### ISSUE THREAD

**Issue by sa-he** [XAMLMarkupExtensions/WPFLocalizationExtension#247]
My initial implementation of TranslateConverter had a virtual Convert method. I have additional custom converters (not reusable for other purposes) that inherit from TranslateConverter. Could you make it virtual, so I can use your implemtation?

**Comment by konne** [comment]
Hi, yes on one side this is not difficult, but I don't understand that this will help.
If you just override the whole function you can also just define a new one.
If you just like to have a baseclass you can also use TypeValueConverterBase that is introduced and have the advantage of the converter xaml without staticresource just with Converter={lex:TranslateConverter}

**Comment by konne** [comment]
@sa-he please give feedback

**Comment by sa-he** [comment]
I have another converter that inherits the base functionality of translation and then modifies the result according to user-defined rules that match my business logic. Yes, this is not a common requirement.

**Comment by konne** [comment]
I don't see the advantage of a virtual method for that. You could easily just make a new class, make inside of this class an instance of the translate converter and just call it like you would call base.Convert
even if it is not perfect I think this would work.
Can we close this issue?

**Comment by sa-he** [comment]
Ok, I'll do that.
