### ISSUE TITLE
Change return value for not existing keys or make it configurable.

### ISSUE THREAD

**Issue by sa-he** [XAMLMarkupExtensions/WPFLocalizationExtension#248]
I stumbled across that during testing your implementation of TranslateConverter with multibinding. My initial TranslateConverter used as fallback value the given resource-key while your's returns `new object()` which is provided by LocExtension.GetLocalizedValue(..).

ResxLocalizationProviderBase.GetLocalizedObject currently returns null if the resource is not found and also it fires an event `ProviderError`.
Idea: The event `ProviderError` could be extended, so that a consumer can handle it and provide the return value which subsequently is going to be returned by ResxLocalizationProviderBase.

Background: In a release build I like my app to display the resource key itself if no localization text is provided. In debug mode I like to be visually notified by seeing e.g. $"?{resourceKey}?". With the previous described idea this would be possible.

**Comment by konne** [comment]
I will update the TranslareConverter. The PR will available in some minutes

**Comment by konne** [comment]
please check branch changes in #249 this should complete solve your issue. Please see the HelloWorld app for an short example to deliver own MissingKey results. Please add here your CheckDesignTime / check Debug / Release,
I think this should be handle for each use case.

**Comment by sa-he** [comment]
Thank you for your very swift response. If I see it correctly the change is applied for LocExtension as well as TranslateConverter, but not for the others like BLoc or FELoc etc. What do you think of adding that functionality to central translate methods like `ResxLocalizationProviderBase.GetLocalizedObject()`? This way we had that feature for every possible way of translation.

**Comment by konne** [comment]
@sa-he I was already thinking of todo that but not in the current phase.
All this need a big architecture review and rework and I have at the moment not the
time and focusing more on current issues.
Todo:
- [ ] FELoc
- [ ] BLoc
and than is at the moment enough.

**Comment by sa-he** [comment]
It's ok to me! Personally, I do not use FELoc, but BLoc a lot.

**Comment by konne** [comment]
@sa-he please check the dev branch, I have added missing key for BLoc

**Comment by sa-he** [comment]
I've integrated the current pre-release in one of my smaller projects and it is working nicely! In my point of view, this ticket can be closed. Thanks!
