### ISSUE TITLE
LocExtension: add support for TemplateBinding

### ISSUE THREAD

**Issue by Karnah** [XAMLMarkupExtensions/WPFLocalizationExtension#256]
Related with #254

In templates there are two ways of binding to templated control:
- By TemplateBinding
``` xaml
<TextBlock Text="{lex:Loc {TemplateBinding Message}}" />
```

- By Binding using RelativeSource
``` xaml
<TextBlock Text="{lex:Loc {Binding RelativeSource={RelativeSource TemplatedParent}, 
                                   Path=Message}}" />
```

First way is a more simple, but it is not supported now

**Comment by konne** [comment]
@Karnah please can you provide a PR with working sample of the second approach.
I will after that take care that TemplateBinding will work

**Comment by konne** [comment]
@Karnah ignore my last comment

**Comment by konne** [comment]
@Karnah I added this feature to the dev branch, please check it, if it working like you expected

**Comment by Karnah** [comment]
@konne, yes, it looks as I expected. Thanks a lot.
I'll check it with future version of package, but I think it will work nice.
