### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by koronakaren** [XAMLMarkupExtensions/WPFLocalizationExtension#262]
Please refer to:
https://stackoverflow.com/questions/49260388/prevent-wpflocalizeextension-from-trying-to-load-resources-for-all-possible-lang

I beleive this is adding 9+ seconds to my apps start up time.   Limiting culture thru a configuration mechanism might be an option?

**Comment by konne** [comment]
Hi,

the issue is that this mechanism is used to get a list of all available cultures.
I will have a look if it would be possible to disable or limit  this feature to solve this issue.

bye

**Comment by koronakaren** [comment]
Thank you Konne.  Maybe it could stated in app.config section.

**Comment by konne** [comment]
@koronakaren you can define your own searchlist in the next release please see:

https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/development/docs/FAQ.md#startuptime-for-available-cultures-search-with-resx-provider
