### ISSUE TITLE
Support for .net core

### ISSUE THREAD

**Issue by hnmange** [XAMLMarkupExtensions/WPFLocalizationExtension#263]
How to use it with WPF .net core application ?

**Comment by konne** [comment]
Hi, this example is compiles as .netcore.
https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/master/tests/HelloWorldWPF/HelloWorldWPF.csproj
I hope that answers your question. If you have an issue just reopen this ticket.
