### ISSUE TITLE
Binding, formatting and Lex:Loc

### ISSUE THREAD

**Issue by LinoBarreca** [XAMLMarkupExtensions/WPFLocalizationExtension#288]
Hi. I read all the documentation and after hours I can't combine the three concepts above.
I have to set a caption through binding, taking the resources to format the string.
Bind to "Name"
Resource key "Welcome" with contents "Welcome {0}"

Without lex:Loc I can write
`something.Caption= "{Binding Name, StringFormat=Welcome{0}}"
`
and it works. It sets the caption to _Welcome Lino_
with
`something.Caption="{lex:Loc Welcome}"
`
and it works: It sets the caption to the localized resource pointed by key which, in english, contains _Welcome {0}_

Any other try or combination to achieve what I want throws exception. For example
`something.Caption= "{Binding Name, StringFormat={lex:Loc Welcome}}"
` (ArgumentException, complaining about value but anyway I didn't expect it to work because you say that you provided a StringFormatConverter because of that)

I even wrote my own converter, trying to pass the output of lex:Loc as a converter parameter
"{Binding IOName, Converter={StaticResource StringFormatConverter}, ConverterParameter={lex:Loc ManipulateInputValue}}">
But that seems to completely make the binding go crazy because it searches for the "Value" property (Which I never requested) on the ViewModel...

> System.Windows.Data Error: 40 : BindingExpression path error: 'Value' property not found on 'object' ''WelcomeViewModel' (HashCode=36222803)'. BindingExpression:Path=Value; DataItem='WelcomeViewModel' (HashCode=36222803); target element is 'WelcomeDialog' (Name=''); target property is 'Caption' (type 'String')

How can I combine the three things together?

**Comment by Karnah** [comment]
Hello, @LinoBarreca. If you need use localized string as format string - you should use MultiBinding with StringFormatConverter.
It's neccessary, because both 'StringFormat' and 'ConverterParameter' doesn't support `Binding` (it is WPF behavior)

Sample:
``` xaml
<TextBlock>
    <TextBlock.Text>
        <MultiBinding Converter="{lex:StringFormatConverter}" >
            <Binding Source="{lex:Loc Welcome}" />
            <Binding Name />
        </MultiBinding>
    </TextBlock.Text>
</TextBlock>
```

I didn't work much with "code behind markup", but probably you can change my sample to your needs.

**Comment by LinoBarreca** [comment]
Hi @Karnah 

> Hello, @LinoBarreca. If you need use localized string as format string - you should use MultiBinding with StringFormatConverter.
> It's neccessary, because both 'StringFormat' and 'ConverterParameter' doesn't support `Binding` (it is WPF behavior)

Tried this as well with this code:
```
        <MultiBinding Converter="{lex:StringFormatConverter}">
            <lex:BLoc Key="Welcome"/>
            <Binding Path="Name"/>
        </MultiBinding>
```
 but, in my case, I still have two problems:

1) the databinding seems to not work property: the window has a weird effect because (I don't know why) the converter seems to return the viewmodelname so the window is created/shown with that wrong caption and after a  0,4 sec the converter kicks in, translates properly and the caption is set to the correct value. This makes the window change while the user sees it...

2) I can not compile the code "as is" because the Caption is an (externally) attached property to the UserControl. So I must declare the caption (attached:Caption="blabla") as attribute of the usercontrol (XML) element and I must write the multibinding in one line and it seems it isn't possible. So I should extend the usercontrol to add a regular dependencyproperty instead of using an attached one.
It looks like an overkill to me.

**Comment by Karnah** [comment]
1. Hmm. It's weird. When and where you set Provider for LocalizeDictionary? Probably you use ResxLocalizationProvider. If you set it code behind, probably screen will show before it set. 

2. If I correctly understand your problem, you can use MultiBinding with attached properties. Just for sample, like this:
``` xaml
<TextBlock>
    <lex:LocalizeDictionary.Provider>
        <MultiBinding>
            TODO
        </MultiBinding>
    </lex:LocalizeDictionary.Provider>
</TextBlock>
```
Instead `lex:LocalizeDictionary.Provider` use `YourNamespace:YourAttachedPropertiesClass.AttachedProperty`. It should work.

**Comment by Karnah** [comment]
1. Could you create a sample project with this problem? I don't have any ideas now.
2. You can define your `UserControl` like this:
``` xaml
<UserControl Grid.Column="1">
    <local:AttachedProperties.AttachedProperty>
        <MultiBinding StringFormat="{}{0} {1}">
            <Binding Source="aba" />
            <Binding Source="caba" />
        </MultiBinding>
    </local:AttachedProperties.AttachedProperty>
    
    <UserControl.Content>
        <TextBlock Text="Abacaba" />
    </UserControl.Content>
</UserControl>
```

**Comment by LinoBarreca** [comment]
The solution you proposed for point 2 worked (thanks about that, I never used it that way, you never stop learning).
Without the double binding it also it solved the problem in point 1.
Thank you.
