### ISSUE TITLE
StringFormatConverter should support converting to object

### ISSUE THREAD

**Issue by mark-monteiro** [XAMLMarkupExtensions/WPFLocalizationExtension#291]
StringFormatConverter currently throws an exception if the target type is not `string`, but a target type of `object` is also valid. For example, I think the following should be supported:

```cs
<Button>
    <Button.ToolTip>
        <MultiBinding Converter="{lex:StringFormatConverter}">
            <Binding Path="FormatProperty" />
            <Binding Path="FormatArgumentProperty"/>
        </MultiBinding>
    </Button.ToolTip>
</Button>
```

To address this I think the [existing check](https://github.com/XAMLMarkupExtensions/WPFLocalizationExtension/blob/master/src/ValueConverters/StringFormatConverter.cs#L50) in `StringFormatConverter` should be changed to this:

```cs
// if (targetType != typeof(string))
if (targetType.IsAssignableFrom(typeof(string))
    throw new Exception("Only target types assignable from string are allowed");
```

**Comment by Karnah** [comment]
Duplicated #279. Also already there is PR for this bug #280 .
@konne, could you check and publish new release? :)

**Comment by mark-monteiro** [comment]
Thanks, I searched the existing issues before opening this one but missed that. I'll close this issue
