### ISSUE TITLE
Publish Debug Symbols to NuGet

### ISSUE THREAD

**Issue by mark-monteiro** [XAMLMarkupExtensions/WPFLocalizationExtension#292]
Can the debugging symbols for this library be published to NuGet in the next release?

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

**Comment by konne** [comment]
@mark-monteiro 
At the moment the symbols are directly embedded into the main NuGet. So debugging should already work.
So why this change is necessary for you?

**Comment by mark-monteiro** [comment]
Sorry, I didn't realize the symbols were already embedded into the NuGet package.

What I was trying to do was debug one of the classes in the NuGet package (I think `StringFormatConverter`) and I couldn't figure out how to do that. It sounds like something I need to figure out on my end if the symbols are already in the NuGet package. 

Thanks for responding, I'll close this issue.
