### ISSUE TITLE
Unit tests are failing randomly

### ISSUE THREAD

**Issue by centrolutions** [XAMLMarkupExtensions/WPFLocalizationExtension#297]
I have certain unit tests that are setting the Culture property like this:
```
var newCulture = new CultureInfo(cultureCode);
LocalizeDictionary.Instance.SetCurrentThreadCulture = true;
LocalizeDictionary.Instance.Culture = newCulture;

```
The last line above sometimes throws a NullReferenceException or an InvalidOperationException. Other times, it seems no exception is thrown, but the wrong language is retrieved.

Here are some exceptions:
```
Message: 
    System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace: 
    LocalizeDictionary.set_Culture(CultureInfo value)
    LocalizedStrings.SetCulture(String cultureCode) line 25
```
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
[xUnit.net 00:00:00.68]       Stack Trace:
[xUnit.net 00:00:00.68]            at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
[xUnit.net 00:00:00.68]            at WPFLocalizeExtension.Engine.LocalizeDictionary.set_Culture(CultureInfo value)
[xUnit.net 00:00:00.68]         C:\Users\jason\Source\Repos\StorageCalc\StorageCalc\Resources\LocalizedStrings.cs(25,0): at StorageCalc.Resources.LocalizedStrings.SetCulture(String cultureCode)
```

I should also mention the strings are being retrieved like this:
```
var result = LocalizeDictionary.Instance.GetLocalizedObject("MyAssemblyName", "Strings", key, LocalizeDictionary.Instance.Culture);
return result as string;

```
So, it seems the setter for the Culture property is malfunctioning -- but only sometimes which is causing random tests to fail during one run, but not the next.

Am I setting the culture and retrieving strings correctly? Is this perhaps a niche threading issue with XUnit?

Also, it would be nice if there was a interface to mock during unit testing. This would also be useful for IOC.

**Comment by eriove** [comment]
I use XUnit's `CollectionAttribute` to avoid running multiple localization tests at the same time. Each test is disposable. In the constructor I set the `LocalizeDictionary.Instance.DefaultProvider` to a mock and in `Dispose()` I return it to the original value. We don't have any test that tests changing culture, but I imagine that could work in the same way.

**Comment by Karnah** [comment]
`LocalizeDictionary` is singleton and `LocalizeDictionary.set_Culture` is not thread safe (if i not mistaken it's because you can change this property only in main thread otherwise WPF will have problem with updating UI). Please, disable parallel execution of unit tests and try again.
You can disable parallelism using `CollectionAttribute` ([described here](https://xunit.net/docs/running-tests-in-parallel)) or using Configuration Files with attribute `"parallelizeTestCollections" : false` ([described here](https://xunit.net/docs/configuration-files#parallelizeTestCollections)).

**Comment by SeriousM** [comment]
May I ask why you're don't set the test language fix to eg. "en"?
imho, localization isn't a thing you should test if you just use the XAMLMarkupExtensions package.

**Comment by centrolutions** [comment]
Thanks for the info / feedback everyone. I figured it was because XUnit was running things in a multi-threaded way. I will start using the CollectionAttribute on localized tests so they don't interfere with each other.

**Comment by centrolutions** [comment]
@Karnah thank you for the links and information -- especially the configuration file parameter. I found that I had to use that. The CollectionAttribute seemed to have no effect on its own. The `"parallelizeTestCollections" : false` solved the problem though. Thank you!
